//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelephonShop.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Telephon
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> TelephoneId { get; set; }
        public Nullable<int> UseTimeId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Telephone Telephone { get; set; }
        public virtual UseTime UseTime { get; set; }
    }
}
